import serial
#ard=serial.Serial('com6',9600)
ard=open('my.txt','r')

def mf(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(psp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(nsp)
	ard.flush()
	ard.readline()
def mb(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(nsp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(psp)
	ard.flush()
	ard.readline()
	
def rr(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(psp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(psp)
	ard.flush()
	ard.readline()
def lr(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(nsp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(nsp)
	ard.flush()
	ard.readline()
def tu(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(psp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(psp)
	ard.flush()
	ard.readline()
def td(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(nsp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(nsp)
	ard.flush()
	ard.readline()
def yr(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(psp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	
def yl(offset):
	psp=offset.encode()
	nsp=str(-1*(int(offset))).encode()
	ard.write(nsp)
	ard.readline()
	ard.write(psp)
	ard.readline()
	ard.write(nsp)
	ard.readline()
	ard.write(psp)
	ard.flush()
	ard.readline()
	